# Generated by Django 2.0.2 on 2018-02-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='request_sources_access',
            field=models.CharField(max_length=50),
        ),
    ]
