# Generated by Django 2.0.2 on 2018-02-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_auto_20180220_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='badge_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='info_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_sources_access',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='returned_data_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
