# Generated by Django 2.0.2 on 2018-02-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_auto_20180220_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
