# Generated by Django 2.0.2 on 2018-02-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0003_auto_20180222_2041'),
        ('project_admin', '0003_project_token'),
    ]

    operations = [
    ]
