# Generated by Django 2.0.2 on 2018-02-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0004_merge_20180225_2232'),
        ('project_admin', '0004_project_user'),
    ]

    operations = [
    ]
