# Generated by Django 2.0.3 on 2018-03-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0005_merge_20180226_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='badge_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
