# Generated by Django 2.0.3 on 2018-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0006_auto_20180308_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
