# Generated by Django 2.0.3 on 2018-03-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0007_auto_20180319_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='group',
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='groups',
            field=models.ManyToManyField(to='project_admin.ProjectGroup'),
        ),
    ]
