# Generated by Django 2.0.5 on 2018-05-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0008_auto_20180320_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='username',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='message_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='sources_shared',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
