# Generated by Django 2.0.5 on 2018-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0010_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(max_length=65),
        ),
    ]
