# Generated by Django 2.0.5 on 2018-06-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0011_auto_20180607_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_url',
            field=models.URLField(max_length=512),
        ),
    ]
