# Generated by Django 2.0.7 on 2018-08-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0013_s3upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='message_permission',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
