# Generated by Django 2.0.7 on 2018-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0015_project_refreshed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='oh_file_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('oh_file_id', 'project')},
        ),
    ]
