# Generated by Django 2.0.7 on 2018-11-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0016_auto_20181001_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3upload',
            name='key',
            field=models.CharField(max_length=260),
        ),
    ]
