# Generated by Django 2.0.7 on 2019-04-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0017_auto_20181107_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='request_message_permission',
        ),
    ]
